config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  get   'users/:id'   =>  'users#show'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(title: post_params[:title], text: post_params[:text], user_id: current_user.id)
    
      if  @post.save
        redirect_to @post
      else
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end


  private
    def post_params
      params.require(:post).permit(:title, :text)
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @posts = current_user.posts.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<h1>こんにちは！ww</h1>
<%= link_to "投稿一覧へ", controller: "posts" %>

app/views/comments/_comment.html.erb
<p>
  <strong>コメンター:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>コメント:</strong>
  <%= simple_format comment.body %>
</p>

<p>
  <%= link_to 'コメント削除', [comment.post, comment],
              method: :delete, data: { comfirm: '削除しますか？w' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for( [@post, @post.comments.build] ) do |f| %>
  <p>
    <%= f.label :commenter, "コメンター" %><br />
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body, "コメント" %><br />
    <%= f.text_area :body, cols: 60, rows: 8 %>
  </p>

  <p>
    <%= f.submit "コメント投稿" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOGAPP</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
  <div id="wrap">

    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">ブログアプリ</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.nickname %>
              <ul class="user__info">
                <li>
                  <a href="/users/<%= current_user.id %>">マイページ</a>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <a class="post" href="/posts/new">投稿する</a>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
            <%= link_to "ユーザ登録", new_user_registration_path, :class => 'post' %>
          </div>
        <% end %>
      </div>
    </header>

    <div id="main">
    <%= yield %>
    </div>

    <footer>
      <p>
        Copyright PicTweet 2019.
      </p>
    </footer>

  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーが発生したため保存ができませんでした。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text, "内容" %><br>
    <%= f.text_area :text, cols: 60, rows: 8 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿を更新</h1>

<%= render 'form'%>

<%= link_to '戻る', posts_path %>

app/views/posts/index.html.erb
<h1>全ての投稿</h1>

<table>
  <tr>
    <th>ニックネーム</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.user.nickname %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      
      <% if user_signed_in? && current_user.id == post.user_id %>
        <td><%= link_to '詳細', post %></td>
        <td><%= link_to '編集', edit_post_path(post) %></td>
        <td><%= link_to '削除', post_path(post),
                    method: :delete, data: { confirm: '削除しますか？w'} %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>

<%= render 'form' %>

<%= link_to '戻る', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>タイトル：</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>内容：</strong>
  <%= simple_format @post.text %>
</p>


<h2>コメント</h2>
<%= render @post.comments %> 
 
<h2>コメントを追加</h2>
<%= render "comments/form" %>

<%= link_to '戻る', posts_path %>
| <%= link_to '編集', edit_post_path(@post) %>

app/views/users/show.html.erb
    <h1><%= @nickname %>の投稿一覧❤️</h1>
    
    <table>
      <tr>
        <th>ニックネーム</th>
        <th>タイトル</th>
        <th>内容</th>
      </tr>

    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.nickname %></td>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
      </tr>
    <% end %>
    </table>

        <%= link_to '戻る', posts_path %>